# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 15:29
from __future__ import unicode_literals

import app_blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_remove_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=app_blog.models.upload_location),
        ),
    ]
