# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_auto_20160824_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 8, 25, 13, 59, 33, 274055, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
